#!/usr/bin/python

import sys
import re

err = [];
out = [];
EMPTY_ANSWER = "Ans = []"

with open (sys.argv[1],"r") as f:
    err = f.readlines()

with open (sys.argv[2],"r") as f:
    out = f.readlines()

ep = 19
op = 0

while ep != len(err):
    if ep > len(err):
        print >> sys.stderr, "Error pointer goes out of bounds"
        sys.exit(1)
    if err[ep].startswith('true ?'):
        print out[op].strip()
        op += 1
        ep += 2
    elif err[ep].startswith('! Existence') or err[ep].startswith('! Domain'):
        print EMPTY_ANSWER
        ep += 3
    elif re.match('[A-Z] = ',err[ep]) or err[ep].startswith('! Inst'):
        print EMPTY_ANSWER
        ep += 2
    elif err[ep].startswith('no'):
        print EMPTY_ANSWER
        ep += 1
    else:
        print >> sys.stderr, "Unrecognized pattern generated by SICSTUS", err[ep]
        sys.exit(1)

